[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "wexample-pseudocode"
version = "0.0.8"
description = "Code creation and maintenance tools"
authors = [
    { name = "weeger", email = "contact@wexample.com" },
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/wexample/python-pseudocode"

[tool.setuptools]
packages = [
    "wexample_pseudocode",
]
